name: "Build Docker Image"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    container: docker

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      run: docker build --tag pyspark-pipeline .
