name: "Tests"
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make requirements

    - name: Checks
      run: make checks

    - name: Tests
      run: make tests
